{
 "title": "java tron server",
 "description": "Monitor your java-tron server with Prometheus and Grafana.",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "6s",
 "templating": {
  "list": [
   { "name": "instance", "label": "instance", "query": { "query": "label_values(instance)" } },
   { "name": "group", "label": "group", "query": { "query": "label_values(group)" } }
  ]
 },
 "panels": [
  { "title": "Chain", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Start Time",
   "type": "gauge",
   "description": "Start time of the  java-tron process since unix epoch in seconds.",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "dateTimeAsIso" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "process_start_time_seconds{group=`$group`,instance=`$instance`}* 1000"
    }
   ]
  },
  {
   "title": "Up Time",
   "type": "gauge",
   "description": "Up Time is a measure of system reliability, expressed as the percentage of time java-tron process, has been working and available",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "time() - process_start_time_seconds{group=`$group`,instance=`$instance`}"
    }
   ]
  },
  {
   "title": "Header Height",
   "type": "stat",
   "description": "The latest block height of java-tron on this node.",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "tron:header_height{group=`$group`,instance=`$instance`}",
     "legendFormat": "Header height"
    }
   ]
  },
  {
   "title": "Header Time",
   "type": "stat",
   "description": "The latest block time of java-tron on this node.",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "dateTimeAsIso" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "tron:header_time{group=`$group`,instance=`$instance`}",
     "legendFormat": "Header height"
    }
   ]
  },
  { "title": "System", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "CPUS",
   "type": "stat",
   "description": "The number of processors available to the java virtual machine.",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "system_available_cpus{group=`$group`,instance=`$instance`}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "stat",
   "description": "Total: total physical memory.\n\nFree: free physical memory.",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "system_total_physical_memory_bytes{group=`$group`,instance=`$instance`}",
     "legendFormat": "Total"
    },
    {
     "expr": "system_free_physical_memory_bytes{group=`$group`,instance=`$instance`}",
     "legendFormat": "Free"
    }
   ]
  },
  {
   "title": "Load Average",
   "type": "timeseries",
   "description": "The system load average for the last minute. The system load average is the sum of the number of runnable entities queued to the available processors and the number of runnable entities running on the available processors averaged over a period of time. The way in which the load average is calculated is operating system specific but is typically a damped time-dependent average.",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "system_load_average{group=`$group`,instance=`$instance`}",
     "legendFormat": "load average"
    }
   ]
  },
  {
   "title": "Open Fds",
   "type": "stat",
   "description": "Max: maximum number of open file descriptors. \n\nCurrent: number of open file descriptors.",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "process_max_fds{group=`$group`,instance=`$instance`}",
     "legendFormat": "Max"
    },
    {
     "expr": "process_open_fds{group=`$group`,instance=`$instance`}",
     "legendFormat": "Current"
    }
   ]
  },
  { "title": "JVM", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 } },
  {
   "title": "JVM Version",
   "type": "stat",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "label_join(jvm_info{group=\"$group\",instance=\"$instance\"}, \"jdk\", \", \", \"vendor\", \"runtime\", \"version\")"
    }
   ]
  },
  {
   "title": "Memory Usage Rate ",
   "type": "timeseries",
   "description": "JVM heap used /  JVM heap max.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(jvm_memory_bytes_used{group=`$group`,instance=`$instance`})/sum(jvm_memory_bytes_init{group=`$group`,instance=`$instance`})",
     "legendFormat": "Usage"
    }
   ]
  },
  {
   "title": "Memory Used",
   "type": "graph",
   "description": "JVM heap detail.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "jvm_memory_bytes_used{group=`$group`,instance=`$instance`,area=\"heap\"}",
     "legendFormat": "{{area}}"
    },
    {
     "expr": "jvm_memory_pool_bytes_used{group=`$group`,instance=`$instance`}",
     "legendFormat": "{{pool}}"
    }
   ]
  },
  {
   "title": "GC Time/Minute",
   "type": "graph",
   "description": "GC time every minute.",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 27 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "increase(jvm_gc_collection_seconds_sum{group=\"$group\",instance=~\"$instance\"}[$__interval])",
     "legendFormat": "{{gc}}"
    }
   ]
  },
  {
   "title": "GC Count/Minute",
   "type": "graph",
   "description": "GC count every minute.",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 27 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(jvm_gc_collection_seconds_count{group=\"$group\",instance=~\"$instance\"}[$__interval])",
     "legendFormat": "{{gc}}"
    }
   ]
  },
  { "title": "Txs", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 36 } },
  {
   "title": "Pending Pool",
   "type": "timeseries",
   "description": "Waiting for packed tansactions, including pending and repush.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 37 },
   "targets": [
    {
     "expr": "sum(tron:manager_queue_size{group=`$group`,instance=`$instance`,type !=`popped`,type !=`queued`})",
     "legendFormat": "pending pool"
    }
   ]
  },
  {
   "title": " Transactions / Block",
   "type": "timeseries",
   "description": "Average of the number of transactions in a block within 1 minute.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 37 },
   "targets": [
    {
     "expr": "delta(tron:txs_total{group=`$group`,instance=`$instance`,type=\"success\"}[60s])/20",
     "legendFormat": "trxs/block"
    }
   ]
  },
  {
   "title": " Transaction TPS",
   "type": "graph",
   "description": "Average transaction TPS.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 45 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(tron:process_transaction_latency_seconds_count{group=`$group`,instance=`$instance`,type=\"trx\"}[$__interval]))",
     "legendFormat": "total"
    },
    {
     "expr": "rate(tron:process_transaction_latency_seconds_count{group=`$group`,instance=`$instance`,type=\"trx\"}[$__interval])",
     "legendFormat": "{{contract}}"
    }
   ]
  },
  {
   "title": "Transaction Process Latency",
   "type": "graph",
   "description": "Average transaction processing time.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "  sum(increase(tron:process_transaction_latency_seconds_sum{group=`$group`,instance=`$instance`,type = `trx`}[$__interval])) \n/\n  sum(increase(tron:process_transaction_latency_seconds_count{group=`$group`,instance=`$instance`,type = `trx`}[$__interval]))",
     "legendFormat": "avg"
    },
    {
     "expr": "  increase(tron:process_transaction_latency_seconds_sum{group=`$group`,instance=`$instance`,type = `trx`}[$__interval]) \n/\n  increase(tron:process_transaction_latency_seconds_count{group=`$group`,instance=`$instance`,type = `trx`}[$__interval])",
     "legendFormat": "{{contract}}"
    }
   ]
  },
  { "title": "Block", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 53 } },
  {
   "title": "Block Generate Latency",
   "type": "graph",
   "description": "Average block generate time .",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 54 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "  rate(tron:block_generate_latency_seconds_sum{group=`$group`,instance=`$instance`,sync =\"false\"}[$__interval])\n/\n  rate(tron:block_generate_latency_seconds_count{group=`$group`,instance=`$instance`,sync =\"false\"}[$__interval])",
     "legendFormat": "avg"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(tron:block_generate_latency_seconds_bucket{group=`$group`,instance=`$instance`,sync =\"false\"}[$__interval])) by (le))",
     "legendFormat": "tp99"
    }
   ]
  },
  {
   "title": "Block Process Latency",
   "type": "graph",
   "description": "Average block processing time when is not catching up.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 54 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "  rate(tron:block_process_latency_seconds_sum{group=`$group`,instance=`$instance`,sync =\"false\"}[$__interval])\n/\n  rate(tron:block_process_latency_seconds_count{group=`$group`,instance=`$instance`,sync =\"false\"}[$__interval])",
     "legendFormat": "avg"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(tron:block_process_latency_seconds_bucket{group=`$group`,instance=`$instance`,sync =\"false\"}[$__interval])) by (le))",
     "legendFormat": "tp99"
    }
   ]
  },
  {
   "title": "Verify Transactions Signature Latency",
   "type": "timeseries",
   "description": "Average  parallel verification transactions signature processing time.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 62 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "  rate(tron:verify_sign_latency_seconds_sum{group=`$group`,instance=`$instance`}[$__interval])\n/\n  rate(tron:verify_sign_latency_seconds_count{group=`$group`,instance=`$instance`}[$__interval])",
     "legendFormat": "avg"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(tron:verify_sign_latency_seconds_bucket{group=`$group`,instance=`$instance`}[$__interval])) by (le))",
     "legendFormat": "tp99"
    }
   ]
  },
  {
   "title": "Net",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 70 },
   "collapsed": true,
   "panels": [
    {
     "title": "Peers",
     "type": "gauge",
     "description": "Node peers Info.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 71 },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "tron:peers{group=`$group`,instance=`$instance`}",
       "legendFormat": "{{type}}"
      }
     ]
    },
    {
     "title": "Ping Pong Latency",
     "type": "timeseries",
     "description": "Peers ping pong latency.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 71 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.99, sum(rate(tron:ping_pong_latency_seconds_bucket{group=`$group`,instance=`$instance`}[$__interval])) by (le,type))",
       "legendFormat": "tp99"
      },
      {
       "expr": "  increase(tron:ping_pong_latency_seconds_sum{group=`$group`,instance=`$instance`}[$__interval])\n/\n  increase(tron:ping_pong_latency_seconds_count{group=`$group`,instance=`$instance`}[$__interval])",
       "legendFormat": "avg"
      }
     ]
    },
    {
     "title": "HTTP Traffic /10 Minutes",
     "type": "timeseries",
     "description": "Http network data traffic statistics.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 79 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "increase(tron:http_bytes_sum{group=`$group`,instance=`$instance`}[10m])",
       "legendFormat": "{{url}}.{{status}}"
      }
     ]
    },
    {
     "title": "TCP Traffic/10 Minutes ",
     "type": "timeseries",
     "description": "TCP network data traffic statistics.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 79 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "increase(tron:tcp_bytes_sum{group=`$group`,instance=`$instance`}[$__interval])",
       "legendFormat": "{{type}}"
      }
     ]
    }
   ]
  },
  {
   "title": "API",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 71 },
   "collapsed": true,
   "panels": [
    {
     "title": " HTTP QPS",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 80 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(tron:http_service_latency_seconds_count{group=`$group`,instance=`$instance`}[$__interval]))",
       "legendFormat": "total"
      },
      {
       "expr": "rate(tron:http_service_latency_seconds_count{group=`$group`,instance=`$instance`}[$__interval])",
       "legendFormat": "{{url}}"
      }
     ]
    },
    {
     "title": "HTTP Latency",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 80 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "rate(tron:http_service_latency_seconds_sum{group=`$group`,instance=`$instance`}[$__interval])/rate(tron:http_service_latency_seconds_count{group=`$group`,instance=`$instance`}[$__interval])",
       "legendFormat": "{{url}}"
      }
     ]
    },
    {
     "title": " GRPC QPS",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 88 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(tron:grpc_service_latency_seconds_sum{group=`$group`,instance=`$instance`}[$__interval]))",
       "legendFormat": "total"
      },
      {
       "expr": "rate(tron:grpc_service_latency_seconds_count{group=`$group`,instance=`$instance`}[$__interval])",
       "legendFormat": "{{endpoint}}"
      }
     ]
    },
    {
     "title": "GRPC Latency",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 88 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "rate(tron:grpc_service_latency_seconds_sum{group=`$group`,instance=`$instance`}[$__interval])/rate(tron:grpc_service_latency_seconds_count{group=`$group`,instance=`$instance`}[$__interval])",
       "legendFormat": "{{endpoint}}"
      }
     ]
    }
   ]
  },
  {
   "title": "DB",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 72 },
   "collapsed": true,
   "panels": [
    {
     "title": "total",
     "type": "stat",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 97 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "sum(tron:db_size_bytes{group=`$group`,instance=`$instance`,type = \"LEVELDB\"})",
       "legendFormat": "total"
      },
      {
       "expr": "sum(delta(tron:db_size_bytes{group=`$group`,instance=`$instance`,type = \"LEVELDB\"}[24h]))",
       "legendFormat": "delta/24H"
      }
     ]
    },
    {
     "title": "block",
     "type": "stat",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 103 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "sum(tron:db_size_bytes{group=`$group`,instance=`$instance`,type=\"LEVELDB\",db=\"block\"})",
       "legendFormat": "block"
      },
      {
       "expr": "sum(delta(tron:db_size_bytes{group=`$group`,instance=`$instance`,type = \"LEVELDB\",db=\"block\"}[24h]))",
       "legendFormat": "delta/24H"
      }
     ]
    },
    {
     "title": "transactionRetStore",
     "type": "stat",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 103 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "sum(tron:db_size_bytes{group=`$group`,instance=`$instance`,type=\"LEVELDB\",db=\"transactionRetStore\"})",
       "legendFormat": "transactionRetStore"
      },
      {
       "expr": "sum(delta(tron:db_size_bytes{group=`$group`,instance=`$instance`,type = \"LEVELDB\",db=\"transactionRetStore\"}[24h]))",
       "legendFormat": "delta/24H"
      }
     ]
    },
    {
     "title": "trans",
     "type": "stat",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 109 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "sum(tron:db_size_bytes{group=`$group`,instance=`$instance`,type=\"LEVELDB\",db=\"trans\"})",
       "legendFormat": "trans"
      },
      {
       "expr": "sum(delta(tron:db_size_bytes{group=`$group`,instance=`$instance`,type = \"LEVELDB\",db=\"trans\"}[24h]))",
       "legendFormat": "delta/24H"
      }
     ]
    },
    {
     "title": "transactionHistoryStore",
     "type": "stat",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 109 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "sum(tron:db_size_bytes{group=`$group`,instance=`$instance`,type=\"LEVELDB\",db=\"transactionHistoryStore\"})",
       "legendFormat": "transactionHistoryStore"
      },
      {
       "expr": "sum(delta(tron:db_size_bytes{group=`$group`,instance=`$instance`,type = \"LEVELDB\",db=\"transactionHistoryStore\"}[24h]))",
       "legendFormat": "delta/24H"
      }
     ]
    },
    {
     "title": "storage-row",
     "type": "stat",
     "gridPos": { "h": 5, "w": 12, "x": 0, "y": 115 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "sum(tron:db_size_bytes{group=`$group`,instance=`$instance`,type=\"LEVELDB\",db=\"storage-row\"})",
       "legendFormat": "storage-row"
      },
      {
       "expr": "sum(delta(tron:db_size_bytes{group=`$group`,instance=`$instance`,type = \"LEVELDB\",db=\"storage-row\"}[24h]))",
       "legendFormat": "delta/24H"
      }
     ]
    },
    {
     "title": "account",
     "type": "stat",
     "gridPos": { "h": 5, "w": 12, "x": 12, "y": 115 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "sum(tron:db_size_bytes{group=`$group`,instance=`$instance`,type=\"LEVELDB\",db=\"account\"})",
       "legendFormat": "account"
      },
      {
       "expr": "sum(delta(tron:db_size_bytes{group=`$group`,instance=`$instance`,type = \"LEVELDB\",db=\"account\"}[24h]))",
       "legendFormat": "delta/24H"
      }
     ]
    },
    {
     "title": "delegation",
     "type": "stat",
     "gridPos": { "h": 5, "w": 12, "x": 0, "y": 120 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "sum(tron:db_size_bytes{group=`$group`,instance=`$instance`,type=\"LEVELDB\",db=\"delegation\"})",
       "legendFormat": "delegation"
      },
      {
       "expr": "sum(delta(tron:db_size_bytes{group=`$group`,instance=`$instance`,type = \"LEVELDB\",db=\"delegation\"}[24h]))",
       "legendFormat": "delta/24H"
      }
     ]
    },
    {
     "title": "block-index",
     "type": "stat",
     "gridPos": { "h": 5, "w": 12, "x": 12, "y": 120 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "sum(tron:db_size_bytes{group=`$group`,instance=`$instance`,type=\"LEVELDB\",db=\"block-index\"})",
       "legendFormat": "block-index"
      },
      {
       "expr": "sum(delta(tron:db_size_bytes{group=`$group`,instance=`$instance`,type = \"LEVELDB\",db=\"block-index\"}[24h]))",
       "legendFormat": "delta/24H"
      }
     ]
    }
   ]
  }
 ]
}